### Login as USER
POST http://localhost:7007/api/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password123"
}

### Login as ADMIN
POST http://localhost:7007/api/auth/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "password123"
}

### Register a new user
POST http://localhost:7007/api/auth/register
Content-Type: application/json

{
  "username": "newuser",
  "password": "password123"
}

### Access protected USER endpoint
GET http://localhost:7007/api/protected/user_demo
AUTHORIZATION: Bearer {{user_token}}

### Access protected ADMIN endpoint
GET http://localhost:7007/api/protected/admin_demo
Authorization: Bearer {{admin_token}}
